export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';

export const REGISTER_REQUEST='REGISTER_REQUEST';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';

export const LOAD_USER_REQUEST='LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS='LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL='LOAD_USER_FAIL';

export const LOAD_USER_TODO_REQUEST='LOAD_USER_TODO_REQUEST';
export const LOAD_USER_TODO_SUCCESS='LOAD_USER_TODO_SUCCESS';
export const LOAD_USER_TODO_FAIL='LOAD_USER_TODO_FAIL';

export const ADD_TODO_REQUEST='ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL='ADD_TODO_FAIL';

export const DELETE_TODO_REQUEST='DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS='DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL='DELETE_TODO_FAIL';

export const UPDATE_TODO_REQUEST='UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS='UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAIL='UPDATE_TODO_FAIL';

export const LOGOUT="LOGOUT";